%% LandmarksPP
%%
% Parses a csv file that holds the pose data for the landmarks. Typically
% generated by Motive. 
% 
% * |_table_ *table*|:
% the table created from reading the csv
%
% * |*options*|:
% optional parameters to easily accommodate changes in the format of the
% csv file.
%
% * |_uint32_ *row*|:
% the row at which the data in the file begins
%
% * |_uint32_ *col*|:
% the column at which the data in the file begins   
%
% * |_Nx3 matrix_ *landmarks*|:
% N is the number of landmarks. Each row represents the mean x y z
% coordinates of the landmark.
%

function landmarks = LandmarksPP(table, options)

    %%
    % Define arguments and defaults
    arguments
        table
        options.row (1,1) uint32 = 7
        options.col (1,1) uint32 = 3
    end
    
    %%
    % Get the desired rows and columns from the table
    chunk = table(options.row:end,options.col:end);
    
    %%
    % Convert the table to a matrix, the string values to numbers, and
    % remove any missing values. Then take the mean of each column.
    meanvals = mean(rmmissing(str2double(table2array(chunk))));
    
    %%
    % Get the desired mean values.
    % Indices shown are to skip the x y z rotation columns given in the csv that is
    % automatically generated by Motive.
    landmarks = [meanvals(4:6:end)' meanvals(5:6:end)' meanvals(6:6:end)'];

end

%% Example
% Say your data is positioned on row 8 in the excel instead, then do:
%
%   LandmarksPP(table, 'row', 8)
%   LandmarksPP(table, row=8) 